# version: '2.2'

# services:
#   db:
#     image: postgres
#     environment: 
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code/
#     ports:
#       - "8000:8000"
#       # chcemy aby serwis web uruchamiał się dopiero kiedy wstanie kontener db
#     depends_on:
#       - db